version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: "sandok"  # Set password here for root
      MYSQL_DATABASE: nia                   # Database to be created
      MYSQL_USER: root
      MYSQL_PASSWORD: "sandok"       # Password for root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
